#轻量端节点相关表
#应用参数表
- tableName: sm_appparam
  sql: select * from sm_appparam where PARENTID in (select PK_APPREGISTER from sm_appregister where CODE = ?)
#菜单注册
- tableName: sm_appmenuitem
  sql: select APPCODE,APPID,DR,MENUDES,MENUITEMCODE,MENUITEMNAME,PARENTCODE,PK_GROUP,PK_MENU,PK_MENUITEM,RESID,TS from sm_appmenuitem where APPID in (select PK_APPREGISTER from sm_appregister where CODE = ?)
#页面表
- tableName: sm_apppage
  sql: select CREATIONTIME,CREATOR,DR,ISCARDDEFAULT,ISDEFAULT,MODIFIEDTIME,MODIFIER,PAGECODE,PAGEDESC,PAGENAME,PAGEURL,PARENT_ID,PARENTCODE,PK_APPPAGE,RESID,TS from sm_apppage where PARENT_ID in (select PK_APPREGISTER from sm_appregister where CODE = ?)
#按钮表
- tableName: sm_appbutnregister
  sql: select APPID,BTNAREA,BTNCODE,BTNCOLOR,BTNDESC,BTNNAME,BTNORDER,BTNTYPE,DR,ISENABLE,ISKEYFUNC,KEYBOARD,PAGEAREACODE,PAGECODE,PARENT_CODE,PK_BTN,RESID,TS from sm_appbutnregister where APPID in (select PK_APPREGISTER from sm_appregister where CODE = ?)
#查询方案
- tableName: pub_ncc_queryscheme
  sql: select * from pub_ncc_queryscheme where AREAID in (select PK_AREA from pub_area where TEMPLETID in (select PK_PAGE_TEMPLET from pub_page_templet where APPCODE = ?))
#表格/表单属性
- tableName: pub_form_property
  sql: select AREAID,CLASSID,CODE,COLNUM,COLOR,CREATIONTIME,CREATOR,DATATYPE,DATAVAL,DEFAULTVALUE,DEFAULTVAR,DEFINE1,DEFINE2,DEFINE3,DISABLED,DR,EDITFORMULA,HYPERLINKFLAG,ISCODE,ISDEFINED,ISLOCK,ISMULTISELECTEDENABLED,ISNEXTROW,ISRESLABEL,ISREVISE,ISSYNCFOLD,ISSYNCLIST,ISSYNCSIDE,ISTOTAL,ITEMTYPE,LABEL,MAXLENGTH,METADATAPROPERTY,METAID,METAPATH,MOBILETITLE,MODIFIEDTIME,MODIFIER,ONLYLEAFCANSELECT,PK_FORM_PROPERTY,POSITION,PROID,REFCODE,REFNAME,RELATEMETA,REQUIRED,RESID,SHOWDATAVAL,SHOWFOCUS,SHOWFORMULA,TEXTROWS,TS,VALIDATEFORMULA,VISIBLE,WIDTH from pub_form_property where AREAID in (select PK_AREA from pub_area where TEMPLETID in (select PK_PAGE_TEMPLET from pub_page_templet where APPCODE = ?))
#查询模板
- tableName: pub_query_property
  sql: select AREAID,CLASSID,CODE,CONTAINLOWER,CREATIONTIME,CREATOR,DATATYPE,DATAVAL,DEFAULTVALUE,DEFINE1,DEFINE2,DEFINE3,DEFINE4,DEFINE5,DISABLED,DR,ISBEYONDORG,ISCHECK,ISDEFINED,ISFIXEDCONDITION,ISMULTISELECTEDENABLED,ISNOTMETA,ISQUERYCONDITION,ISRESLABEL,ISUSE,ITEMTYPE,LABEL,MAXLENGTH,METADATAPROPERTY,METAPATH,MOBILETITLE,ONLYLEAFCANSELECT,OPERSIGN,OPERSIGNNAME,PK_QUERY_PROPERTY,POSITION,PROID,QUERYTABLENAME,REFCODE,REFNAME,REQUIRED,RESID,RETURNTYPE,SHOWDATAVAL,SHOWFOCUS,SHOWTYPE,TABLECODE,TS,USEFUNC,VISIBLE,VISIBLEPOSITION,WIDTH from pub_query_property where AREAID in (select PK_AREA from pub_area where TEMPLETID in (select PK_PAGE_TEMPLET from pub_page_templet where APPCODE = ?))
#区域
- tableName: pub_area
  sql: select AREADESC,AREAHIDE,AREASTATUS,AREATYPE,ASSOCIATEDTAB,ASSOCIATEDTABLAYOUT,CLAZZ,CODE,CREATIONTIME,CREATOR,DR,ISGRANDSON,ISUNFOLD,METAID,METANAME,METASPACE,MODIFIEDTIME,MODIFIER,NAME,PAGINATION,PK_AREA,POSITION,RELATIONCODE,RESID,TEMPLETID,TS from pub_area where TEMPLETID in (select PK_PAGE_TEMPLET from pub_page_templet where APPCODE = ?)
#模板
- tableName: pub_page_templet
  sql: select APPCODE,CLAZZ,CODE,CREATIONTIME,CREATOR,DR,HEADCODE,ISDEFAULT,METAID,MODIFIEDTIME,MODIFIER,NAME,PAGECODE,PARENTID,PK_GROUP,PK_ORG,PK_PAGE_TEMPLET,RESID,RESMODULE,TEMPLETDESC,TS from pub_page_templet where APPCODE = ?
#应用表
- tableName: sm_appregister
  sql: select APP_DESC,APPTYPE,CODE,CREATIONTIME,CREATOR,DR,FUN_PROPERTY,FUNTYPE,HEIGHT,HELP_NAME,IMAGE_SRC,ISCAUSERUSABLE,ISCOPYPAGE,ISENABLE,MDID,MODIFIEDTIME,MODIFIER,MOUNTID,NAME,ORGTYPECODE,OWN_MODULE,PARENT_ID,PK_APPREGISTER,PK_GROUP,RESID,SCOPEID,SOURCE_APP_CODE,TARGET_PATH,TS,USELICENSE_LOAD,WIDTH from sm_appregister where CODE = ?